### ISSUE TITLE
sourcemap style.css.map?

### ISSUE THREAD

**Issue by mibamur** [jekyll/jekyll-sass-converter#12]
Hi!
 Thank for work and I have one question.
sourcemap for css - how can I add it or which params I must pass

**Comment by jglovier** [comment]
I would also love to see sourcemaps, but even just a `style: debug` param for the `_config.yml` would be super helpful (prints Sass line numbers and file names in the rendered CSS).

e.g.:

```scss
/* line 39, ../scss/includes/_layout.scss */
  .site-nav:hover {
    background: #0099ff; }
    /* line 41, ../scss/includes/_layout.scss */
    .site-nav:hover .links {
      display: block; }
    /* line 45, ../scss/includes/_layout.scss */
    .site-nav:hover .nav-trigger .menu-icon {
      display: inline-block; }
```
