### ISSUE TITLE
Invalid struct field type #<FFI::Type::Builtin:POINTER size=8 alignment=8> (TypeError)

### ISSUE THREAD

**Issue by vivi90** [jekyll/jekyll-sass-converter#129]
I want to use `@use` so i need to use the Dart Sass implementation.

My `Gemfile` plugin part:
```ruby
group :jekyll_plugins do
  gem "jekyll-sass-converter", github: "jekyll/jekyll-sass-converter"
  gem "sass-embedded"
  gem "jekyll-last-modified-at", "~> 1.3"
# gem "jekyll-github-metadata", "~> 2.13"
# gem "jekyll-gist", "~> 1.5"
# gem "classifier-reborn", "~> 2.2"
  gem "jekyll-seo-tag", "~> 2.7", ">= 2.7.1"
# gem "jekyll-paginate", "~> 1.1"
# gem "jekyll-feed", "~> 0.12"
# gem "jekyll-sitemap", "~> 1.4"
end
```

My `Gemfile.lock`:
```ruby
GIT
  remote: https://github.com/eventmachine/eventmachine.git
  revision: 9cb13a8a62363df5ebcc414169a3deb2c1608528
  tag: v1.2.7
  specs:
    eventmachine (1.2.7)

GIT
  remote: https://github.com/jekyll/jekyll-sass-converter.git
  revision: 5d130e8791fc45f60ca7b41c1926b1ee8bf1e279
  specs:
    jekyll-sass-converter (2.1.0)
      sassc (> 2.0.1, < 3.0)

GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    colorator (1.1.0)
    concurrent-ruby (1.1.9)
    em-websocket (0.5.2)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    fastimage (2.2.5)
    ffi (1.15.4)
    ffi (1.15.4-x64-mingw32)
    forwardable-extended (2.6.0)
    google-protobuf (3.19.1-x64-mingw32)
    google-protobuf (3.19.1-x86_64-linux)
    http_parser.rb (0.6.0)
    i18n (1.8.10)
      concurrent-ruby (~> 1.0)
    jekyll (4.2.1)
      addressable (~> 2.4)
      colorator (~> 1.0)
      em-websocket (~> 0.5)
      i18n (~> 1.0)
      jekyll-sass-converter (~> 2.0)
      jekyll-watch (~> 2.0)
      kramdown (~> 2.3)
      kramdown-parser-gfm (~> 1.0)
      liquid (~> 4.0)
      mercenary (~> 0.4.0)
      pathutil (~> 0.9)
      rouge (~> 3.0)
      safe_yaml (~> 1.0)
      terminal-table (~> 2.0)
    jekyll-last-modified-at (1.3.0)
      jekyll (>= 3.7, < 5.0)
      posix-spawn (~> 0.3.9)
    jekyll-seo-tag (2.7.1)
      jekyll (>= 3.8, < 5.0)
    jekyll-watch (2.2.1)
      listen (~> 3.0)
    kramdown (2.3.1)
      rexml
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    liquid (4.0.3)
    listen (3.7.0)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    mercenary (0.4.0)
    pathutil (0.16.2)
      forwardable-extended (~> 2.6)
    posix-spawn (0.3.15)
    public_suffix (4.0.6)
    rb-fsevent (0.11.0)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rexml (3.2.5)
    rouge (3.26.1)
    safe_yaml (1.0.5)
    sass-embedded (0.9.3)
      google-protobuf (~> 3.19.0)
    sassc (2.4.0)
      ffi (~> 1.9)
    sassc (2.4.0-x64-mingw32)
      ffi (~> 1.9)
    terminal-table (2.0.0)
      unicode-display_width (~> 1.1, >= 1.1.1)
    thread_safe (0.3.6)
    tzinfo (1.2.9)
      thread_safe (~> 0.1)
    tzinfo-data (1.2021.2)
      tzinfo (>= 1.0.0)
    unicode-display_width (1.8.0)
    wdm (0.1.1)
    webrick (1.7.0)

PLATFORMS
  x64-mingw32
  x86_64-linux

DEPENDENCIES
  eventmachine (= 1.2.7)!
  fastimage (~> 2.2, >= 2.2.5)
  jekyll (~> 4.2.0)
  jekyll-last-modified-at (~> 1.3)
  jekyll-sass-converter!
  jekyll-seo-tag (~> 2.7, >= 2.7.1)
  sass-embedded
  tzinfo (~> 1.2)
  tzinfo-data
  wdm (~> 0.1.1)
  webrick (~> 1.7)

BUNDLED WITH
   2.2.30
```

My `config.yml` sass part:
```yml
sass:
  implementation    : sass-embedded # Compiler (Possible values: 'sassc' [default] for LibSass [DEPRECATED], 'sass-embedded' for Dart Sass [requires Ruby 2.6 or higher])
  style             : expanded # The style of the CSS-output (Possible values: 'expanded', 'nested', 'compact', or 'compressed').
  sass_dir          : _sass # A filesystem-path which should be searched for Sass partials.
  load_paths        : [] # An array of additional filesystem-paths which should be searched for Sass partials.
  line_comments     : true # Include the line number and filename of the source in the compiled CSS-file.
  sourcemap         : always # Controls when source maps shall be generated (Possible values: 'never', 'always' or 'development').
```
Interesting: If i set `implementation    : sassc`, the issues not changes.

I used `bundle install` and `bundle clean` after every cahnge.

- Ruby version: `3.0.2p107 (2021-07-07 revision 0db68f0233) [x64-mingw32]`
- OS: `Windows 10 Pro Build 19043`
