### ISSUE TITLE
Front Matter causes error with sass-embedded

### ISSUE THREAD

**Issue by qiz-li** [jekyll/jekyll-sass-converter#135]
Hi. I am trying to move to `sass-embedded` to use `@use`. In my Gemfile, I have

```ruby
gem 'sass-embedded', '~> 1.0'
```

and I also changed the implementation in `_config.yml`

```yaml
sass:
  implementation: sass-embedded
```

However when I try to serve the Jekyll site, it causes this error:

```
Configuration file: /Users/qiz-li/my_jekyll/_config.yml
            Source: /Users/qiz-li/my_jekyll
       Destination: /Users/qiz-li/my_jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
Error: expected "{".
  ╷
4 │ @import "main";
  │               ^
  ╵
  assets/css/main.scss 4:15  @import
  assets/css/main.scss 1:9   root stylesheet
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    expected "{".
/Users/qiz-li/.gem/ruby/3.1.0/gems/jekyll-sass-converter-2.2.0/lib/jekyll/converters/scss.rb:223:in `rescue in sass_embedded_convert': expected "{". (Jekyll::Converters::Scss::SyntaxError)
        from /Users/qiz-li/.gem/ruby/3.1.0/gems/jekyll-sass-converter-2.2.0/lib/jekyll/converters/scss.rb:214:in `sass_embedded_convert'
```

When I change the implementation back to `implementation: sassc` the error disappears, and Jekyll serves fine.
I have not changed the contents of the Sass files.

**`assets/css/main.scss:`**

```scss
---
---

@import "main";
```

**`_sass/main.scss:`**

```scss
$backgroundColor: #ffffff;
$bodyColor: #000000;
$bodyFont: -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";

body {
  background: $backgroundColor;
  color: $bodyColor;
  font-family: $bodyFont;
}
```

I am on:

- Ruby: `ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-darwin21]`
- OS: `macOS Monterey Version 12.2.1`

Thanks for any help.
