### ISSUE TITLE
Simplify using gems for load_paths

### ISSUE THREAD

**Issue by pmwmedia** [jekyll/jekyll-sass-converter#138]
I want to use Bootstrap 5.2 for my page. Therefore, I have added `gem "bootstrap", "~> 5.2.0"` to my `Gemfile`. Afterwards, I have added the full absolute path to Bootstrap to `load_paths` in my `_config.yml`:

```yml
sass:
  load_paths:
    - _sass
    - C:/ruby3/lib/ruby/gems/3.1.0/gems/bootstrap-5.2.0/assets/stylesheets
```

Now, I can import Bootstrap successfully via `@import "bootstrap";` in my `main.scss`. However, the absolute path is very ugly! Other users have to use the same operation system and must install Ruby in the same folder.

It would be great, if a placeholder instead of the absolute path could be used. I think about something like this:

```yml
sass:
  load_paths:
    - _sass
    - $GEM_HOME/bootstrap-5.2.0/assets/stylesheets
```
