### ISSUE TITLE
How to hide sass warnings?

### ISSUE THREAD

**Issue by ncarandini** [jekyll/jekyll-sass-converter#170]
I have a Jekyll site and I have upgraded it to the latest Jekyll 4.4. Alas I use Bootstrap 5 and I have many warnings from saas (hope BS will eventually fix their sass files with @use instead of @import and other things that are deprecated since Dart Sass 1.8.0.
Anyway, I can live with it because at the end of the day the command `bundle exec jekyll serve --force_polling --incremental` eventually works.

To get rid of these annoying warnings, I've followed the instructions and updated the `_config.yml` file with the sass options:

```
sass:
  sass_dir: ./css
  quiet_deps: true
```
please note that the tree structure of my project is something like:

```
> root-folder
  > _data
  > _include
  > _layout
  ...
  > assets
  > css
    > bootstrap
    > custom
    main.scss
  > scripts
  _config.yml
  ...
  index.html
  ...
```
But I still receive the warnings. What I'm doing wrong? Thanks in advance for any help.

**Comment by ashmaroli** [comment]
Hello @ncarandini,
I have released v3.1.0 of this plugin that supports additional configuration to address deprecation warnings.

After installing the latest version of this plugin, update your config file to contain:
```yaml
# _config.yml

sass:
  quiet_deps: true
  silence_deprecations: [import]

**Comment by ncarandini** [comment]
Thank you so much!
 I've updated the plugin deleting the `Gemfile.lock` file and executing the command:
```
bundle install
```
Then I've modified the `config.yml` file adding all the annoying warning:
```
sass:
  sass_dir: ./css
  quiet_deps: true
  silence_deprecations:
    - import
    - global-builtin
    - color-functions
    - mixed-decls
    - abs-percent
    - function-units
    - color-functions
    - abs-percent
```

And everything now works like a charm, no more warnings! 👍 
Again, thank you!!!
