### ISSUE TITLE
Support for asset_url helper

### ISSUE THREAD

**Issue by jglovier** [jekyll/jekyll-sass-converter#30]
Would love to see support for the `asset_url` helper which compiles something like:

```scss
.fence { background-image: image-url("bg-fence.jpg"); }
```
into
```scss
.fence { background-image: url("../img/bg-fence.jpg");}
```
