### ISSUE TITLE
Incorrect Documentation (cache: false)

### ISSUE THREAD

**Issue by leehambley** [jekyll/jekyll-sass-converter#36]
The Jekyll docs here http://jekyllrb.com/docs/assets/  report that "These are passed to Sass, so any output style options Sass supports are valid here, too.".

The list of [supported Sass options](http://sass-lang.com/documentation/file.SASS_REFERENCE.htm) is extensive.

My goal was to disable caching, by setting the following in my Jekyll v2.5.3 `_config.yml`:

```
highlighter: pygments

exclude: ['Gemfile', 'Gemfile.lock', 'Guardfile' ]

sass:
  sass_dir: dist/sass
  cache: false
```

However, I notice only a handful of options are supported, and `cache` is always overwritten with a value derived from `safe?`:

 * https://github.com/jekyll/jekyll-sass-converter/blob/master/lib/jekyll/converters/scss.rb#L89

Would you take a PR to fix this, or with Jekyll 3 just around the corner, will this gem die, and expect to be replaced with jekyll-assets?
