### ISSUE TITLE
iPhone X safe-area-inset error

### ISSUE THREAD

**Issue by jcontonio** [jekyll/jekyll-sass-converter#66]
Following the examples from [Apple's documentation](https://webkit.org/blog/7929/designing-websites-for-iphone-x/), v1.5.1 will throw an error for the following:

```scss
@supports(padding: max(0px)) {
    padding-left: max($marginWidth, env(safe-area-inset-left));
    padding-right: max($marginWidth, env(safe-area-inset-right));
  }
```

The error: `"env(safe-area-inset-left)" is not a number for `max'`
